
if idaapi.IDA_SDK_VERSION >= 740:
    from ida_nalt import STRTYPE_C_16 as ASCSTR_UNICODE
    from ida_kernwin import ask_buttons as askbuttons_c
    from ida_lines import add_extra_cmt as add_long_cmt
    from ida_auto import auto_unmark as autoUnmark
    from ida_nalt import STRTYPE_C_16 as ASCSTR_UTF16
    from ida_kernwin import msg as umsg
    from ida_bytes import char_flag as charflag
    from ida_bytes import get_max_strlit_length as get_max_ascii_length
    from ida_bytes import is_char1 as isChar1
    from ida_graph import GraphViewer as GraphViewer
    from ida_bytes import print_strlit_type as print_ascii_string_type
    from ida_kernwin import ask_long as asklong
    do3byte = lambda *args: False
    from ida_bytes import FF_YWORD as FF_YWRD
    from ida_ida import idainfo as idainfo
    from ida_bytes import DELIT_EXPAND as DOUNK_EXPAND
    from ida_kernwin import ask_yn as askyn_c
    from ida_kernwin import open_form as OpenForm
    from ida_kernwin import PluginForm as PluginForm
    from ida_ua import insn_t as insn_t
    from ida_typeinf import for_all_const_arglocs as for_all_const_varlocs
    from ida_bytes import create_oword as doOwrd
    from ida_nalt import V695_REF_VHIGH as REF_VHIGH
    from ida_kernwin import ask_form as AskUsingForm
    from ida_nalt import SWI_INDIRECT >> 16 as SWI2_INDIRECT
    from ida_kernwin import PluginForm as PluginForm
    from ida_segregs import sreg_range_t as segreg_area_t
    from ida_expr import calc_idc_expr as old_func
    from ida_problems import is_problem_present as QueueIsPresent
    from ida_auto import plan_ea as noUsed
    invalidate_visea_cache = lambda *args: False
    from ida_ida import AF_SIGCMT as AF2_SIGCMT
    from ida_expr import set_idc_func_ex as old_func
    from ida_kernwin import user_cancelled as wasBreak
    from ida_ida import AF_HFLIRT as AF2_HFLIRT
    from ida_bytes import create_tbyte as doTbyt
    from ida_bytes import create_double as doDouble
    from ida_nalt import get_op_tinfo as old_func
    from ida_nalt import STRTYPE_TERMCHR as ASCSTR_TERMCHR
    from ida_ua import decode_preceding_insn as old_func
    from ida_ua import decode_preceding_insn as old_func
    from ida_ida import AF_JUMPTBL as AF2_JUMPTBL
    from ida_bytes import is_word as isWord
    from ida_expr import dosysfile as old_func
    from ida_kernwin import PluginForm as PluginForm
    from ida_ida import idainfo as idainfo
    from ida_segment import CSS_NORANGE as CSS_NOAREA
    from [ida_ida import idainfo as idainfo
    from ida_bytes import has_xref as hasRef
    from ida_nalt import del_tinfo2 as old_func
    from ida_range import range_t as range_t
    from ida_nalt import STRTYPE_LEN2_16 as ASCSTR_ULEN2
    from ida_idp import CUSTOM_INSN_ITYPE as CUSTOM_CMD_ITYPE
    from ida_segment import SEGMOD_SILENT as SEGDEL_SILENT
    from ida_problems import cvar as Q_badstack
    from ida_bytes import update_hidden_range as update_hidden_area
    from ida_enum import get_enum_member_serial as get_const_serial
    from ida_ida import idainfo as idainfo
    from ida_bytes import is_double as isDouble
    from ida_bytes import create_dword as doDwrd
    from ida_typeinf import print_type as print_type3
    from ida_bytes import stkvar_flag as stkvarflag
    from ida_idp import ph_get_reg_data_sreg as ph_get_regDataSreg
    from ida_struct import get_or_guess_member_tinfo as old_func
    from ida_ida import idainfo as idainfo
    from ida_bytes import del_hidden_range as del_hidden_area
    from ida_ida import show_all_comments as showAllComments
    from ida_bytes import add_hidden_range as add_hidden_area
    from ida_ua import ua_add_cref as old_func
    from ida_enum import set_enum_member_name as set_const_name
    from ida_expr import idcv_string as VarString2
    from ida_enum import get_prev_serial_enum_member as get_prev_serial_const
    from ida_kernwin import PluginForm as PluginForm
    from ida_problems import cvar as Q_noFop
    from ida_typeinf import print_type as print_type2
    from ida_bytes import is_mapped as isEnabled
    from ida_idp import changing_range_cmt as changing_area_cmt
    from ida_segregs import get_sreg as get_segreg
    from ida_idp import has_insn_feature as InstrIsSet
    from ida_typeinf import gen_decorate_name3 as old_func
    from ida_bytes import f_is_double as f_isDouble
    from ida_bytes import is_tbyte as isTbyt
    from ida_expr import move_idcv as VarMove
    from ida_kernwin import display_widget as open_tform
    from ida_bytes import off_flag as offflag
    from ida_queue import get_short_queue_name as old_func
    from ida_graph import get_node_info as get_node_info2
    from ida_diskio import generic_linput_t as generic_linput64_t
    from ida_problems import remember_problem as QueueSet
    from ida_kernwin import get_current_widget as get_current_tform
    from ida_expr import compile_idc_text as CompileLine
    from ida_auto import auto_wait as autoWait
    from ida_dbg import get_processes as get_process_qty
    from ida_ida import AF_REGARG as AF2_REGARG
    from ida_bytes import custfmt_flag as custfmtflag
    from ida_netnode import netnode as netnode
    from ida_segregs import get_sreg_range as get_srarea2
    from ida_typeinf import PRALOC_STKOFF as PRVLOC_VERIFY
    from ida_kernwin import ask_text as asktext
    from ida_bytes import data_type_t as data_type_t
    from ida_bytes import is_loaded as isLoaded
    from ida_typeinf import parse_decl2 as old_func
    from ida_bytes import word_flag as wordflag
    from ida_kernwin import close_widget as close_tform
    from ida_netnode import netnode as netnode
    from ida_ida import idainfo as idainfo
    from ida_bytes import f_is_dword as f_isDwrd
    from ida_bytes import FF_STRLIT as FF_ASCI
    get_3byte = lambda *args: False
    from ida_typeinf import add_til as add_til2
    from ida_graph import set_node_info as set_node_info2
    from ida_bytes import double_flag as doubleflag
    from ida_ida import STRF_AUTO as ASCF_AUTO
    from ida_bytes import put_bytes as put_many_bytes
    from ida_kernwin import askstr as old_func
    from ida_ida import idainfo as idainfo
    from ida_name import is_ident as isident
    from ida_problems import cvar as Q_att
    from ida_kernwin import Choose as Choose2
    from ida_struct import save_struc as save_struc2
    from ida_typeinf import print_argloc as print_varloc
    from ida_bytes import get_opinfo as old_func
    from ida_range import range_t as area_t
    from ida_typeinf import add_til as old_func
    from ida_typeinf import deref_ptr as deref_ptr2
    from ida_ida import AF_VERSP as AF2_VERSP
    from ida_funcs import func_tail_iterator_set as func_tail_iterator_set2
    from ida_ida import STRF_SAVECASE as ASCF_SAVECASE
    from ida_enum import get_first_enum_member as get_first_const
    from ida_bytes import get_hidden_range_num as get_hidden_area_num
    from ida_nalt import switch_info_t as switch_info_t
    from ida_enum import get_enum_member as get_const
    from ida_bytes import f_is_data as f_isData
    from ida_bytes import get_default_radix as getDefaultRadix
    from ida_funcs import get_func_name as get_func_name2
    from ida_bytes import next_that as nextthat
    from ida_ida import idainfo as idainfo
    from ida_bytes import is_char as isChar
    from ida_auto import auto_is_ok as autoIsOk
    from ida_problems import cvar as Q_jumps
    from ida_expr import calcexpr as old_func
    from ida_kernwin import choose_find as choose2_find
    from ida_bytes import f_is_float as f_isFloat
    from ida_name import validate_name2 as old_func
    from ida_ida import AF_MEMFUNC as AF2_MEMFUNC
    from ida_name import validate_name2 as old_func
    from ida_netnode import netnode as netnode
    from _ida_kernwin import _ask_seg as _askseg
    from ida_enum import set_enum_member_cmt as set_const_cmt
    from ida_nalt import switch_info_t as switch_info_ex_t
    from ida_bytes import get_flags as get_flags_novalue
    from ida_typeinf import apply_tinfo as apply_tinfo2
    from ida_ida import idainfo as idainfo
    from ida_segment import segment_t as segment_t
    from ida_bytes import create_16bit_data as do16bit
    from ida_typeinf import set_compiler as set_compiler2
    from ida_expr import VarGetAttr as old_func
    from ida_kernwin import get_widget_type as get_tform_type
    from ida_bytes import del_items as do_unknown
    from ida_problems import cvar as Q_final
    from ida_expr import compile_idc_file as CompileEx
    from ida_expr import last_idcv_attr as VarLastAttr
    from ida_bytes import get_bytes as get_many_bytes
    from ida_typeinf import scattered_aloc_t as scattered_vloc_t
    from ida_loader import save_database as old_func
    from ida_segregs import split_sreg_range as split_srarea
    from ida_expr import next_idcv_attr as VarNextAttr
    from ida_diskio import create_generic_linput as create_generic_linput64
    from ida_bytes import is_code as isCode
    from ida_bytes import f_is_strlit as f_isASCII
    from ida_nalt import SWI_DEF_IN_TBL as SWI_END_IN_TBL
    from ida_kernwin import pyscv_get_widget as pyscv_get_tcustom_control
    from ida_enum import get_enum_member_by_name as get_const_by_name
    from ida_expr import deref_idcv as VarDeref
    from ida_auto import auto_mark as autoMark
    from ida_bytes import stroff_flag as stroffflag
    choose2_get_embedded_selection = ida_kernwin.lambda *args: None
    from ida_kernwin import ask_file as askfile_c
    from ida_bytes import create_yword as doYwrd
    from ida_bytes import is_head as isHead
    from ida_nalt import V695_REF_VLOW as REF_VLOW
    from ida_name import get_name as old_func
    from ida_bytes import is_enum1 as isEnum1
    from ida_idp import str2reg as str2regf
    from ida_bytes import FF_BYTE as FF_3BYTE
    from ida_bytes import get_strlit_contents as get_ascii_contents
    from ida_ida import idainfo as idainfo
    from ida_expr import idcv_int64 as VarInt64
    from ida_bytes import is_strlit as isASCII
    from ida_kernwin import AST_ENABLE_FOR_WIDGET as AST_ENABLE_FOR_FORM
    from ida_ua import ua_add_off_drefs2 as old_func
    from ida_bytes import FF_QWORD as FF_QWRD
    from ida_nalt import set_op_tinfo as set_op_tinfo2
    from ida_bytes import is_data as isData
    from ida_segregs import split_sreg_range as splitSRarea1
    from ida_bytes import is_custfmt1 as isCustFmt1
    from ida_idp import SETPROC_IDB as SETPROC_COMPAT
    from ida_bytes import qword_flag as qwrdflag
    from ida_bytes import f_is_align as f_isAlign
    from ida_bytes import get_dword as get_long
    from ida_nalt import rename_encoding as change_encoding_name
    from ida_bytes import is_suspop as isVoid
    from ida_typeinf import get_idainfo_by_type as get_idainfo_by_type3
    from ida_nalt import STRTYPE_C_32 as ASCSTR_UTF32
    from ida_nalt import get_refinfo as old_func
    from ida_bytes import hex_flag as hexflag
    from ida_bytes import is_oword as isOwrd
    from ida_kernwin import py_get_ask_form as py_get_AskUsingForm
    from ida_queue import get_long_queue_name as old_func
    from ida_enum import ENUM_MEMBER_ERROR_NAME as CONST_ERROR_ENUM
    from ida_kernwin import pyscv_get_widget as pyscv_get_tform
    from ida_segregs import set_default_sreg_value as set_default_segreg_value
    from ida_typeinf import for_all_arglocs as for_all_varlocs
    from ida_ida import to_ea as toEA
    from ida_bytes import DELIT_SIMPLE as DOUNK_SIMPLE
    from ida_idp import ph_get_reg_first_sreg as ph_get_regFirstSreg
    from ida_bytes import f_is_yword as f_isYwrd
    from ida_segregs import get_sreg_range_num as get_srarea_num
    from ida_bytes import op_stroff as old_func
    from ida_idp import ph_get_reg_code_sreg as ph_get_regCodeSreg
    from ida_nalt import get_op_tinfo as get_op_tinfo2
    from ida_expr import set_idcv_attr as VarSetAttr
    from ida_typeinf import guess_func_tinfo2 as old_func
    from ida_bytes import f_is_tail as f_isTail
    from ida_kernwin import refresh_choosers as refresh_lists
    from ida_ida import AF_ANORET as AF2_ANORET
    from ida_bytes import code_flag as codeflag
    from ida_enum import get_enum_member_name as get_const_name
    from ida_bytes import create_strlit as make_ascii_string
    from ida_loader import save_database as save_database_ex
    from ida_bytes import is_stroff as isStroff
    from ida_problems import get_problem_desc as QueueGetMessage
    from ida_bytes import get_full_flags as getFlags
    from ida_struct import set_member_tinfo as set_member_tinfo2
    from ida_segment import SEGMOD_KILL as SEGDEL_PERM
    from ida_bytes import hidden_range_t as hidden_area_t
    from ida_bytes import is_stkvar1 as isStkvar1
    from ida_enum import get_last_serial_enum_member as get_last_serial_const
    from ida_bytes import is_struct as isStruct
    from ida_bytes import create_struct as doStruct
    from ida_bytes import is_stkvar as isStkvar
    from ida_kernwin import is_chooser_widget as is_chooser_tform
    from ida_name import demangle_name as demangle_name2
    from ida_ida import idainfo as idainfo
    from ida_search import find_suspop as find_void
    from ida_segregs import del_sreg_range as del_srarea
    from ida_typeinf import verify_argloc as verify_varloc
    from ida_bytes import is_custfmt as isCustFmt
    from ida_typeinf import PRALOC_VERIFY as PRVLOC_STKOFF
    from ida_bytes import is_off1 as isOff1
    from ida_ua import get_dtype_by_size as get_dtyp_by_size
    from ida_bytes import is_enum as isEnum
    from ida_kernwin import PluginForm as PluginForm
    from ida_ida import idainfo as idainfo
    from ida_frame import get_frame_part as old_func
    from ida_netnode import netnode as netnode
    from ida_bytes import byte_flag as byteflag
    from ida_nalt import set_switch_info as set_switch_info_ex
    from ida_idp import range_cmt_changed as area_cmt_changed
    from ida_enum import ENUM_MEMBER_ERROR_ILLV as CONST_ERROR_VALUE
    from ida_bytes import is_numop as isNum
    from ida_bytes import chunk_start as chunkstart
    from ida_expr import get_idcv_slice as VarGetSlice
    from ida_idp import struc_align_changed as changed_struc
    from ida_typeinf import optimize_argloc as optimize_varloc
    from ida_bytes import is_fltnum as isFltnum
    from ida_bytes import seg_flag as segflag
    from ida_bytes import num_flag as numflag
    from ida_ua import decode_insn as old_func
    from ida_typeinf import TERR_WRONGNAME as TERR_TOOLONGNAME
    from ida_problems import cvar as Q_head
    from ida_bytes import f_is_qword as f_isQwrd
    from ida_ida import STRF_SERIAL as ASCF_SERIAL
    from ida_bytes import create_float as doFloat
    from ida_bytes import strlit_flag as asciflag
    from ida_struct import get_member_tinfo as get_member_tinfo2
    from ida_enum import get_enum_member_cmt as get_const_cmt
    from ida_typeinf import choose_named_type as choose_named_type2
    from ida_bytes import get_zero_ranges as get_zero_areas
    from ida_name import extract_name as extract_name2
    from ida_bytes import dec_flag as decflag
    from ida_problems import get_problem as QueueGetType
    from ida_bytes import cust_flag as custflag
    from ida_bytes import has_extra_cmts as hasExtra
    from ida_netnode import BADNODE as RIDX_AUTO_PLUGINS
    from ida_name import get_name as get_true_name
    from ida_expr import get_idcv_class_name as VarGetClassName
    from ida_idp import IDP_Hooks as IDP_Hooks
    from ida_enum import ENUM_MEMBER_ERROR_MASK as CONST_ERROR_NAME
    from ida_bytes import is_stroff1 as isStroff1
    from ida_auto import show_auto as showAuto
    from ida_typeinf import argpart_t as varpart_t
    from ida_bytes import is_yword as isYwrd
    from ida_bytes import get_next_hidden_range as get_next_hidden_area
    from ida_bytes import is_pack_real as isPackReal
    from ida_kernwin import choose_refresh as choose2_refresh
    from ida_dbg import get_processes as get_process_info
    from ida_name import is_ident_cp as is_ident_char
    from _ida_kernwin import _ask_addr as _askaddr
    from ida_bytes import enum_flag as enumflag
    from ida_bytes import is_numop1 as isNum1
    from ida_idp import segm_attrs_updated as segm_attrs_changed
    from ida_problems import cvar as Q_lines
    from ida_bytes import patch_dword as patch_long
    from ida_netnode import netnode as netnode
    from ida_kernwin import chtype_srcp as chtype_segreg
    from ida_netnode import netnode as netnode
    from ida_typeinf import resolve_typedef as resolve_typedef2
    from ida_expr import execute as old_func
    from ida_idp import deleting_func_tail as removing_func_tail
    from ida_bytes import has_immd as isImmd
    from ida_fixup import FIXUPF_CREATED as FIXUP_CREATED
    from ida_bytes import get_hidden_range as get_hidden_area
    from ida_ua import op_t as op_t
    from ida_bytes import create_data as do_data_ex
    from ida_bytes import ida_idaapi as doExtra
    from ida_expr import copy_idcv as VarCopy
    from ida_typeinf import get_enum_member_expr as get_enum_member_expr2
    from ida_bytes import is_tail as isTail
    from ida_bytes import is_custom as isCustom
    from ida_segment import segment_t as segment_t
    from ida_ida import idainfo as idainfo
    from ida_bytes import f_is_code as f_isCode
    from ida_ida import AF_TRFUNC as AF2_TRFUNC
    from ida_kernwin import PluginForm as PluginForm
    from ida_bytes import free_chunk as freechunk
    from ida_bytes import add_dword as add_long
    from ida_bytes import is_flow as isFlow
    from ida_enum import add_enum_member as add_const
    scr2idb = ida_ida.lambda thing: thing
    from ida_enum import ENUM_MEMBER_ERROR_ENUM as CONST_ERROR_MASK
    from ida_bytes import is_forced_operand as isFop
    from ida_idd import NO_THREAD as PROCESS_NO_THREAD
    noExtra = lambda *args: False
    from ida_typeinf import load_til as load_til2
    from ida_bytes import is_unknown as isUnknown
    from ida_expr import create_idcv_ref as VarRef
    from ida_enum import get_next_serial_enum_member as old_func
    from ida_strlist import build_strlist as refresh_strlist
    is3byte = lambda *args: False
    from ida_range import range_t as range_t
    from ida_idp import stkpnts_changed as changed_stkpnts
    from ida_bytes import oword_flag as owrdflag
    from ida_kernwin import choose_activate as choose2_activate
    from ida_problems import cvar as Q_decimp
    from ida_enum import get_next_serial_enum_member as get_next_serial_const
    from ida_name import get_debug_name as get_debug_name2
    from ida_bytes import is_seg1 as isSeg1
    from ida_bytes import prev_that as prevthat
    from ida_bytes import create_custdata as doCustomData
    from ida_ua import get_dtype_flag as get_dtyp_flag
    from ida_kernwin import ask_ident as askident
    from ida_funcs import del_func_cmt as old_func
    from ida_idp import SETPROC_LOADER as SETPROC_FATAL
    from ida_bytes import has_value as hasValue
    from ida_problems import cvar as Q_noName
    from ida_enum import get_prev_enum_member as get_prev_const
    from ida_ida import AF_FTAIL as AF2_FTAIL
    from ida_bytes import chunk_size as chunksize
    from ida_bytes import is_byte as isByte
    from ida_bytes import tbyte_flag as tbytflag
    from ida_funcs import FUNC_STATICDEF as FUNC_STATIC
    from ida_ida import STRF_UNICODE as ASCF_UNICODE
    from ida_funcs import set_func_start as func_setstart
    from ida_nalt import STRTYPE_LEN4 as ASCSTR_LEN4
    from ida_ida import show_repeatables as showRepeatables
    from ida_kernwin import py_get_open_form as py_get_OpenForm
    from ida_idaapi import pycim_get_widget as pycim_get_tcustom_control
    from ida_nalt import STRTYPE_LEN4_16 as ASCSTR_ULEN4
    from ida_expr import set_idcv_slice as VarSetSlice
    from ida_bytes import prev_chunk as prevchunk
    from ida_segment import SEGMOD_KEEP as SEGDEL_KEEP
    from ida_kernwin import PluginForm as PluginForm
    from ida_bytes import next_chunk as nextchunk
    from ida_bytes import is_not_tail as isNotTail
    from ida_bytes import doASCI as old_func
    from ida_expr import py_add_idc_func as py_set_idc_func_ex
    clear_func_struct = lambda *args: True
    from ida_bytes import FF_STRUCT as FF_STRU
    from ida_bytes import FF_TBYTE as FF_TBYT
    from ida_nalt import SWI_SUBTRACT >> 16 as SWI2_SUBTRACT
    from ida_bytes import doASCI as old_func
    from ida_kernwin import ask_seg as askseg
    from ida_typeinf import const_aloc_visitor_t as const_vloc_visitor_t
    from ida_bytes import next_addr as nextaddr
    from ida_bytes import dword_flag as dwrdflag
    from ida_ida import AF_STRLIT as AF_ASCII
    from ida_ua import get_immvals as get_operand_immvals
    from ida_bytes import is_float as isFloat
    from ida_fixup import FIXUPF_EXTDEF as FIXUP_EXTDEF
    from ida_bytes import f_is_tbyte as f_isTbyt
    from ida_segment import get_segm_name as get_true_segm_name
    from ida_problems import cvar as Q_collsn
    from ida_ida import STRF_COMMENT as ASCF_COMMENT
    from ida_ida import AF_DATOFF as AF2_DATOFF
    from ida_kernwin import chtype_generic as chtype_generic2
    from ida_ida import OFLG_LZERO as INFFL_LZERO
    from ida_expr import swap_idcvs as VarSwap
    from ida_nalt import get_switch_info as get_switch_info_ex
    from ida_ida import idainfo as idainfo
    from ida_bytes import f_is_not_tail as f_isNotTail
    from ida_funcs import set_func_end as func_setend
    from ida_typeinf import find_tinfo_udt_member as old_func
    from ida_frame import add_auto_stkpnt as add_auto_stkpnt2
    from ida_bytes import is_float1 as isFloat1
    from ida_ida import STRF_GEN as ASCF_GEN
    from ida_bytes import f_has_xref as f_hasRef
    from ida_bytes import get_original_dword as get_original_long
    from ida_problems import cvar as Q_Qnum
    from ida_problems import forget_problem as QueueDel
    from ida_kernwin import PluginForm as PluginForm
    from ida_ida import AF_DODATA as AF2_DODATA
    from ida_bytes import f_is_oword as f_isOwrd
    from ida_idp import parse_reg_name as old_func
    from ida_nalt import STRTYPE_PASCAL as ASCSTR_PASCAL
    from ida_lines import add_extra_line as describe
    from ida_ida import UA_MAXOP as UA_MAXOP
    from ida_kernwin import choose_close as choose2_close
    from ida_bytes import get_bytes_and_mask as get_many_bytes_ex
    from ida_kernwin import clr_cancelled as clearBreak
    from ida_bytes import DELIT_NOTRUNC as DOUNK_NOTRUNC
    from ida_typeinf import argloc_t as varloc_t
    from ida_funcs import func_parent_iterator_set as func_parent_iterator_set2
    from ida_graph import del_node_info as del_node_info2
    from ida_bytes import put_dword as put_long
    from ida_bytes import create_32bit_data as do32bit
    from ida_hexrays import get_widget_vdui as get_tform_vdui
    from ida_segregs import get_sreg_range_qty as get_srareas_qty2
    from ida_bytes import is_defarg1 as isDefArg1
    from ida_enum import get_first_serial_enum_member as get_first_serial_const
    from _ida_kernwin import _ask_long as _asklong
    from ida_bytes import yword_flag as ywrdflag
    from ida_bytes import flt_flag as fltflag
    from ida_nalt import switch_info_t as switch_info_t
    from ida_typeinf import save_tinfo as old_func
    from ida_ida import idainfo as idainfo
    from ida_kernwin import PluginForm as PluginForm
    from ida_bytes import oct_flag as octflag
    from ida_bytes import patch_bytes as patch_many_bytes
    from ida_typeinf import apply_cdecl as apply_cdecl2
    from ida_expr import compile_idc_file as Compile
    from ida_bytes import is_zword as isZwrd
    from ida_bytes import create_qword as doQwrd
    from ida_kernwin import Choose as Choose2
    from ida_bytes import byte_flag as tribyteflag
    from ida_nalt import STRTYPE_LEN2 as ASCSTR_LEN2
    from ida_ua import decode_prev_insn as old_func
    from ida_typeinf import extract_argloc as extract_varloc
    from ida_funcs import func_t as func_t
    from ida_bytes import getn_hidden_range as getn_hidden_area
    from ida_ida import show_comments as showComments
    from ida_ida import idainfo as idainfo
    from ida_bytes import create_word as doWord
    from ida_expr import print_idcv as VarPrint
    from ida_bytes import FF_OWORD as FF_OWRD
    from ida_segregs import get_prev_sreg_range as get_prev_srarea
    from ida_offset import calc_basevalue as calc_reference_basevalue
    from ida_kernwin import ask_addr as askaddr
    from ida_bytes import packreal_flag as packrealflag
    from ida_typeinf import guess_tinfo as old_func
    from ida_nalt import get_encoding_qty as get_encodings_count
    from ida_struct import get_member_name as get_member_name2
    from ida_kernwin import get_widget_title as get_tform_title
    from ida_name import demangle_name as old_func
    from ida_kernwin import CB_INVISIBLE as CB_CLOSE_IDB
    from ida_bytes import get_wide_word as get_full_word
    from ida_bytes import FF_DWORD as FF_DWRD
    from ida_name import is_visible_cp as is_visible_char
    from ida_idp import SETPROC_LOADER_NON_FATAL as SETPROC_ALL
    from ida_enum import get_next_enum_member as get_next_const
    from ida_expr import prev_idcv_attr as VarPrevAttr
    from ida_expr import del_idcv_attr as VarDelAttr
    from ida_bytes import get_wide_dword as get_full_long
    from ida_idp import func_tail_deleted as func_tail_removed
    from ida_netnode import netnode as netnode
    from ida_kernwin import UI_Hooks as UI_Hooks
    from ida_bytes import bin_flag as binflag
    from ida_ida import AF_SIGMLT as AF2_SIGMLT
    from ida_idaapi import pycim_get_widget as pycim_get_tform
    from ida_enum import ENUM_MEMBER_ERROR_VALUE as CONST_ERROR_ILLV
    from ida_bytes import f_is_word as f_isWord
    from ida_enum import get_enum_member_value as get_const_value
    from ida_typeinf import guess_tinfo as guess_tinfo2
    from ida_ida import idainfo as idainfo
    from ida_bytes import set_immd as doImmd
    from ida_bytes import get_hidden_range_qty as get_hidden_area_qty
    idb2scr = ida_ida.lambda thing: thing
    from ida_name import do_name_anyway as old_func
    from ida_bytes import do_unknown_range as old_func
    from ida_ida import idainfo as idainfo
    from ida_bytes import f_is_byte as f_isByte
    from ida_kernwin import find_widget as find_tform
    from ida_auto import set_ida_state as setStat
    from ida_hexrays import hx_get_widget_vdui as hx_get_tform_vdui
    from ida_fixup import FIXUPF_REL as FIXUP_REL
    from ida_ua import create_insn as old_func
    from ida_enum import get_enum_member_bmask as get_const_bmask
    from ida_bytes import create_align as doAlign
    from ida_typeinf import aloc_visitor_t as vloc_visitor_t
    from ida_bytes import create_packed_real as doPackReal
    from ida_bytes import is_align as isAlign
    from ida_problems import cvar as Q_rolled
    from ida_ida import idainfo as idainfo
    from ida_ida import idainfo as idainfo
    from ida_ida import AF_STKARG as AF2_STKARG
    from ida_kernwin import UI_Hooks as UI_Hooks
    from ida_enum import del_enum_member as del_const
    from ida_ida import idainfo as idainfo
    from ida_bytes import create_byte as doByte
    from ida_nalt import get_tinfo as get_tinfo2
    from ida_ua import ua_add_dref as old_func
    from ida_bytes import FF_ZWORD as FF_ZWRD
    from ida_bytes import prev_addr as prevaddr
    from ida_segregs import getn_sreg_range as getn_srarea2
    from ida_bytes import get_prev_hidden_range as get_prev_hidden_area
    from ida_kernwin import AST_DISABLE_FOR_WIDGET as AST_DISABLE_FOR_FORM
    from ida_enum import get_prev_serial_enum_member as old_func
    from ida_ua import dt_byte as dt_3byte
    from ida_bytes import float_flag as floatflag
    from ida_bytes import create_zword as doZwrd
    from ida_ua import ua_dodata2 as old_func
    f_is3byte = lambda *args: False
    from ida_bytes import get_strlit_contents as get_ascii_contents2
    ansi2idb = ida_ida.lambda thing: thing
    from ida_typeinf import apply_cdecl as apply_decl
    from ida_kernwin import activate_widget as switchto_tform
    from ida_ida import idainfo as idainfo
    from ida_bytes import get_radix as getRadix
    from ida_idp import get_reg_info as get_reg_info2
    from ida_bytes import align_flag as alignflag
    from ida_bytes import DELIT_DELNAMES as DOUNK_DELNAMES
    from ida_name import validate_name3 as old_func
    from ida_bytes import get_wide_byte as get_full_byte
    from ida_nalt import set_tinfo as set_tinfo2
    from ida_expr import VT_STR as VT_STR2
    from ida_nalt import switch_info_t as switch_info_t
    from ida_expr import first_idcv_attr as VarFirstAttr
    from ida_ida import idainfo as idainfo
    from ida_nalt import get_tinfo as old_func
    from ida_idp import ph_get_reg_last_sreg as ph_get_regLastSreg
    from ida_enum import get_enum_member_enum as get_const_enum
    from ida_enum import get_last_enum_member as get_last_const
    from ida_funcs import func_t as func_t
    from ida_nalt import del_switch_info as del_switch_info_ex
    from ida_segregs import set_default_sreg_value as SetDefaultRegisterValue
    from ida_ida import AF_DOCODE as AF2_DOCODE
    from ida_typeinf import lower_type as lower_type2
    from ida_segment import del_segment_cmt as old_func
    from ida_ua import get_dtype_size as get_dtyp_size
    from ida_funcs import add_regarg as add_regarg2
    from ida_ua import ua_stkvar2 as old_func
    from ida_bytes import is_func as isFunc
    from ida_bytes import f_is_head as f_isHead
    from ida_offset import calc_target as calc_reference_target
    from ida_segregs import copy_sreg_ranges as copy_srareas
    from ida_ida import AF_CHKUNI as AF2_CHKUNI
    from ida_struct import get_member_tinfo as old_func
    from ida_bytes import f_is_struct as f_isStruct
    from ida_typeinf import find_udt_member as old_func
    from ida_kernwin import set_cancelled as setBreak
    from ida_bytes import stru_flag as struflag
    from ida_bytes import clr_op_type as noType
    from ida_auto import plan_and_wait as analyze_area
    from ida_auto import show_addr as showAddr
    from ida_kernwin import PluginForm as PluginForm
    from ida_problems import cvar as Q_noRef
    from ida_bytes import zword_flag as zwrdflag
    from ida_bytes import is_defarg as isDefArg
    from ida_segregs import get_sreg as getSR
    from ida_kernwin import UI_Hooks as UI_Hooks
    from ida_idp import changing_struc_align as changing_struc
    from ida_netnode import netnode as netnode
    from ida_kernwin import UI_Hooks as UI_Hooks
    from ida_bytes import f_is_custom as f_isCustom
    from ida_problems import cvar as Q_noValid
    from ida_problems import cvar as Q_noBase
    from ida_bytes import is_qword as isQwrd
    from ida_problems import cvar as Q_disasm
    from ida_bytes import is_off as isOff
    from ida_graph import clr_node_info as clr_node_info2
    from ida_bytes import del_value as delValue
    from ida_kernwin import PluginForm as PluginForm
    from ida_kernwin import UI_Hooks as UI_Hooks
    from ida_ida import AF_PURDAT as AF2_PURDAT
    from ida_problems import cvar as Q_noComm
    from ida_bytes import is_seg as isSeg
    from ida_name import make_visible_name as old_func
    from ida_auto import auto_cancel as autoCancel
    from ida_bytes import f_is_pack_real as f_isPackReal
    from ida_typeinf import calc_c_cpp_name as calc_c_cpp_name4
    from ida_frame import get_stkvar as old_func
    from ida_netnode import netnode as netnode
    from ida_bytes import is_dword as isDwrd
    from ida_netnode import netnode as netnode
    from ida_struct import get_or_guess_member_tinfo as get_or_guess_member_tinfo2
    from ida_segment import sel2para as ask_selected
    from ida_ida import idainfo as idainfo
    from ida_netnode import netnode as netnode
    from ida_expr import idcv_object as VarObject
    from ida_typeinf import choose_local_tinfo as choose_local_type
    from ida_bytes import STRCONV_ESCAPE as ACFOPT_ESCAPE
else:
    from ida_kernwin import get_highlighted_identifier as get_highlighted_identifier
    from ida_nalt import ASCSTR_UNICODE as ASCSTR_UNICODE
    from ida_kernwin import askbuttons_c as askbuttons_c
    from ida_lines import add_long_cmt as add_long_cmt
    from ida_auto import autoUnmark as autoUnmark
    from ida_nalt import ASCSTR_UTF16 as ASCSTR_UTF16
    from ida_kernwin import umsg as umsg
    from ida_bytes import charflag as charflag
    from ida_bytes import get_max_ascii_length as get_max_ascii_length
    from ida_bytes import ACFOPT_UTF8 as ACFOPT_UTF8
    from ida_bytes import isChar1 as isChar1
    from ida_graph import GraphViewer as GraphViewer
    from ida_bytes import print_ascii_string_type as print_ascii_string_type
    from ida_kernwin import asklong as asklong
    from ida_bytes import do3byte as do3byte
    from ida_bytes import FF_YWRD as FF_YWRD
    from ida_ida import idainfo as idainfo
    from ida_bytes import DOUNK_EXPAND as DOUNK_EXPAND
    from ida_kernwin import askyn_c as askyn_c
    from ida_kernwin import OpenForm as OpenForm
    from ida_kernwin import PluginForm as PluginForm
    from ida_ua import insn_t as insn_t
    from ida_typeinf import for_all_const_varlocs as for_all_const_varlocs
    from ida_bytes import doOwrd as doOwrd
    from ida_nalt import REF_VHIGH as REF_VHIGH
    from ida_kernwin import AskUsingForm as AskUsingForm
    from ida_nalt import SWI2_INDIRECT as SWI2_INDIRECT
    from ida_kernwin import PluginForm as PluginForm
    from ida_srarea import segreg_area_t as segreg_area_t
    from ida_expr import calc_idc_expr as calc_idc_expr
    from ida_queue import QueueIsPresent as QueueIsPresent
    from ida_auto import noUsed as noUsed
    from ida_bytes import invalidate_visea_cache as invalidate_visea_cache
    from ida_ida import AF2_SIGCMT as AF2_SIGCMT
    from ida_expr import set_idc_func_ex as set_idc_func_ex
    from ida_kernwin import wasBreak as wasBreak
    from ida_ida import AF2_HFLIRT as AF2_HFLIRT
    from ida_bytes import doTbyt as doTbyt
    from ida_bytes import doDouble as doDouble
    from ida_nalt import get_op_tinfo as get_op_tinfo
    from ida_nalt import ASCSTR_TERMCHR as ASCSTR_TERMCHR
    from ida_ua import decode_preceding_insn as decode_preceding_insn
    from ida_pro import strupr as strupr
    from ida_ua import tbo_123 as tbo_123
    from ida_ida import AF2_JUMPTBL as AF2_JUMPTBL
    from ida_bytes import isWord as isWord
    from ida_expr import dosysfile as dosysfile
    from ida_kernwin import PluginForm as PluginForm
    from ida_ida import idainfo as idainfo
    from ida_segment import CSS_NOAREA as CSS_NOAREA
    from ida_ida import idainfo as idainfo
    from ida_bytes import hasRef as hasRef
    from ida_nalt import del_tinfo2 as del_tinfo2
    from ida_range import range_t as range_t
    from ida_nalt import ASCSTR_ULEN2 as ASCSTR_ULEN2
    from ida_idp import CUSTOM_CMD_ITYPE as CUSTOM_CMD_ITYPE
    from ida_segment import SEGDEL_SILENT as SEGDEL_SILENT
    from ida_queue import Q_badstack as Q_badstack
    from ida_bytes import update_hidden_area as update_hidden_area
    from ida_enum import get_const_serial as get_const_serial
    from ida_ida import idainfo as idainfo
    from ida_bytes import isDouble as isDouble
    from ida_bytes import doDwrd as doDwrd
    from ida_typeinf import print_type3 as print_type3
    from ida_bytes import isEnum0 as isEnum0
    from ida_bytes import stkvarflag as stkvarflag
    from ida_idp import ph_get_regDataSreg as ph_get_regDataSreg
    from ida_struct import get_or_guess_member_tinfo as get_or_guess_member_tinfo
    from ida_ida import idainfo as idainfo
    from ida_bytes import del_hidden_area as del_hidden_area
    from ida_ida import showAllComments as showAllComments
    from ida_bytes import add_hidden_area as add_hidden_area
    from ida_ua import ua_add_cref as ua_add_cref
    from ida_enum import set_const_name as set_const_name
    from ida_expr import VarString2 as VarString2
    from ida_enum import get_prev_serial_const as get_prev_serial_const
    from ida_kernwin import PluginForm as PluginForm
    from ida_queue import Q_noFop as Q_noFop
    from ida_typeinf import print_type2 as print_type2
    from ida_ua import ua_dodata as ua_dodata
    from ida_bytes import isEnabled as isEnabled
    from ida_idp import changing_area_cmt as changing_area_cmt
    from ida_srarea import get_segreg as get_segreg
    from ida_idp import InstrIsSet as InstrIsSet
    from ida_typeinf import gen_decorate_name3 as gen_decorate_name3
    from ida_bytes import f_isDouble as f_isDouble
    from ida_bytes import isTbyt as isTbyt
    from ida_expr import VarMove as VarMove
    from ida_kernwin import open_tform as open_tform
    from ida_bytes import offflag as offflag
    from ida_queue import get_short_queue_name as get_short_queue_name
    from ida_graph import get_node_info2 as get_node_info2
    from ida_diskio import generic_linput64_t as generic_linput64_t
    from ida_queue import QueueSet as QueueSet
    from ida_kernwin import get_current_tform as get_current_tform
    from ida_expr import CompileLine as CompileLine
    from ida_auto import autoWait as autoWait
    from ida_dbg import get_process_qty as get_process_qty
    from ida_ida import AF2_REGARG as AF2_REGARG
    from ida_bytes import custfmtflag as custfmtflag
    from ida_netnode import netnode as netnode
    from ida_srarea import get_srarea2 as get_srarea2
    from ida_typeinf import PRVLOC_VERIFY as PRVLOC_VERIFY
    from ida_kernwin import asktext as asktext
    from ida_bytes import data_type_t as data_type_t
    from ida_bytes import isLoaded as isLoaded
    from ida_typeinf import parse_decl2 as parse_decl2
    from ida_bytes import wordflag as wordflag
    from ida_kernwin import close_tform as close_tform
    from ida_netnode import netnode as netnode
    from ida_ida import idainfo as idainfo
    from ida_bytes import f_isDwrd as f_isDwrd
    from ida_bytes import FF_ASCI as FF_ASCI
    from ida_bytes import get_3byte as get_3byte
    from ida_typeinf import add_til2 as add_til2
    from ida_graph import set_node_info2 as set_node_info2
    from ida_bytes import doubleflag as doubleflag
    from ida_ida import ASCF_AUTO as ASCF_AUTO
    from ida_bytes import put_many_bytes as put_many_bytes
    from ida_kernwin import askstr as askstr
    from ida_ida import idainfo as idainfo
    from ida_name import isident as isident
    from ida_queue import Q_att as Q_att
    from ida_kernwin import Choose2 as Choose2
    from ida_struct import save_struc2 as save_struc2
    from ida_bytes import GFE_NOVALUE as GFE_NOVALUE
    from ida_typeinf import print_varloc as print_varloc
    from ida_bytes import get_opinfo as get_opinfo
    from ida_area import area_t as area_t
    from ida_segment import SEGDEL_KEEP0 as SEGDEL_KEEP0
    from ida_typeinf import add_til as add_til
    from ida_typeinf import deref_ptr2 as deref_ptr2
    from ida_ua import tbo_132 as tbo_132
    from ida_ida import AF2_VERSP as AF2_VERSP
    from ida_funcs import func_tail_iterator_set2 as func_tail_iterator_set2
    from ida_ida import ASCF_SAVECASE as ASCF_SAVECASE
    from ida_enum import get_first_const as get_first_const
    from ida_bytes import get_hidden_area_num as get_hidden_area_num
    from ida_nalt import switch_info_t as switch_info_t
    from ida_enum import get_const as get_const
    from ida_bytes import f_isData as f_isData
    from ida_bytes import getDefaultRadix as getDefaultRadix
    from ida_funcs import get_func_name2 as get_func_name2
    from ida_bytes import isDefArg0 as isDefArg0
    from ida_bytes import nextthat as nextthat
    from ida_loader import MAX_FILE_FORMAT_NAME as MAX_FILE_FORMAT_NAME
    from ida_nalt import is_unicode as is_unicode
    from ida_ida import idainfo as idainfo
    from ida_bytes import isChar as isChar
    from ida_auto import autoIsOk as autoIsOk
    from ida_queue import Q_jumps as Q_jumps
    from ida_expr import calcexpr as calcexpr
    from ida_kernwin import choose2_find as choose2_find
    from ida_bytes import f_isFloat as f_isFloat
    from ida_name import validate_name2 as validate_name2
    from ida_ida import AF2_MEMFUNC as AF2_MEMFUNC
    from ida_pro import strlwr as strlwr
    from ida_netnode import netnode as netnode
    from ida_kernwin import _askseg as _askseg
    from ida_enum import set_const_cmt as set_const_cmt
    from ida_nalt import switch_info_ex_t as switch_info_ex_t
    from ida_bytes import get_flags_novalue as get_flags_novalue
    from ida_typeinf import apply_tinfo2 as apply_tinfo2
    from ida_ida import idainfo as idainfo
    from ida_segment import segment_t as segment_t
    from ida_bytes import do16bit as do16bit
    from ida_typeinf import set_compiler2 as set_compiler2
    from ida_expr import VarGetAttr as VarGetAttr
    from ida_kernwin import get_tform_type as get_tform_type
    from ida_bytes import do_unknown as do_unknown
    from ida_kernwin import HIST_ADDR as HIST_ADDR
    from ida_queue import Q_final as Q_final
    from ida_expr import CompileEx as CompileEx
    from ida_expr import VarLastAttr as VarLastAttr
    from ida_bytes import get_many_bytes as get_many_bytes
    from ida_typeinf import scattered_vloc_t as scattered_vloc_t
    from ida_loader import save_database as save_database
    from ida_srarea import split_srarea as split_srarea
    from ida_expr import VarNextAttr as VarNextAttr
    from ida_ua import ua_add_off_drefs as ua_add_off_drefs
    from ida_diskio import create_generic_linput64 as create_generic_linput64
    from ida_bytes import isCode as isCode
    from ida_bytes import f_isASCII as f_isASCII
    from ida_ua import tbo_213 as tbo_213
    from ida_nalt import SWI_END_IN_TBL as SWI_END_IN_TBL
    from ida_kernwin import pyscv_get_tcustom_control as pyscv_get_tcustom_control
    from ida_enum import get_const_by_name as get_const_by_name
    from ida_expr import VarDeref as VarDeref
    from ida_auto import autoMark as autoMark
    from ida_bytes import stroffflag as stroffflag
    from ida_kernwin import choose2_get_embedded_selection as choose2_get_embedded_selection
    from ida_kernwin import askfile_c as askfile_c
    from ida_bytes import doYwrd as doYwrd
    from ida_bytes import isHead as isHead
    from ida_nalt import REF_VLOW as REF_VLOW
    from ida_funcs import get_func_limits as get_func_limits
    from ida_name import get_name as get_name
    from ida_bytes import isEnum1 as isEnum1
    from ida_idp import str2regf as str2regf
    from ida_typeinf import print_type as print_type
    from ida_bytes import FF_3BYTE as FF_3BYTE
    from ida_bytes import get_ascii_contents as get_ascii_contents
    from ida_ida import idainfo as idainfo
    from ida_expr import VarInt64 as VarInt64
    from ida_bytes import isASCII as isASCII
    from ida_kernwin import AST_ENABLE_FOR_FORM as AST_ENABLE_FOR_FORM
    from ida_ua import ua_add_off_drefs2 as ua_add_off_drefs2
    from ida_bytes import FF_QWRD as FF_QWRD
    from ida_nalt import set_op_tinfo2 as set_op_tinfo2
    from ida_bytes import isData as isData
    from ida_srarea import splitSRarea1 as splitSRarea1
    from ida_bytes import isCustFmt1 as isCustFmt1
    from ida_idp import SETPROC_COMPAT as SETPROC_COMPAT
    from ida_bytes import qwrdflag as qwrdflag
    from ida_bytes import f_isAlign as f_isAlign
    from ida_bytes import get_long as get_long
    from ida_nalt import change_encoding_name as change_encoding_name
    from ida_bytes import isVoid as isVoid
    from ida_typeinf import get_idainfo_by_type3 as get_idainfo_by_type3
    from ida_nalt import ASCSTR_UTF32 as ASCSTR_UTF32
    from ida_nalt import get_refinfo as get_refinfo
    from ida_bytes import hexflag as hexflag
    from ida_bytes import isOwrd as isOwrd
    from ida_kernwin import py_get_AskUsingForm as py_get_AskUsingForm
    from ida_queue import get_long_queue_name as get_long_queue_name
    from ida_enum import CONST_ERROR_ENUM as CONST_ERROR_ENUM
    from ida_kernwin import pyscv_get_tform as pyscv_get_tform
    from ida_srarea import set_default_segreg_value as set_default_segreg_value
    from ida_typeinf import for_all_varlocs as for_all_varlocs
    from ida_ida import toEA as toEA
    from ida_offset import set_offset as set_offset
    from ida_bytes import DOUNK_SIMPLE as DOUNK_SIMPLE
    from ida_bytes import isNum0 as isNum0
    from ida_idp import ph_get_regFirstSreg as ph_get_regFirstSreg
    from ida_bytes import f_isYwrd as f_isYwrd
    from ida_srarea import get_srarea_num as get_srarea_num
    from ida_kernwin import Choose2 as Choose2
    from ida_bytes import op_stroff as op_stroff
    from ida_idp import ph_get_regCodeSreg as ph_get_regCodeSreg
    from ida_nalt import get_op_tinfo2 as get_op_tinfo2
    from ida_expr import VarSetAttr as VarSetAttr
    from ida_typeinf import guess_func_tinfo2 as guess_func_tinfo2
    from ida_bytes import f_isTail as f_isTail
    from ida_kernwin import refresh_lists as refresh_lists
    from ida_ida import AF2_ANORET as AF2_ANORET
    from ida_bytes import codeflag as codeflag
    from ida_enum import get_const_name as get_const_name
    from ida_bytes import make_ascii_string as make_ascii_string
    from ida_loader import save_database_ex as save_database_ex
    from ida_bytes import isStroff as isStroff
    from ida_queue import QueueGetMessage as QueueGetMessage
    from ida_bytes import getFlags as getFlags
    from ida_struct import set_member_tinfo2 as set_member_tinfo2
    from ida_segment import SEGDEL_PERM as SEGDEL_PERM
    from ida_bytes import hidden_area_t as hidden_area_t
    from ida_bytes import isStkvar1 as isStkvar1
    from ida_enum import get_last_serial_const as get_last_serial_const
    from ida_bytes import isStruct as isStruct
    from ida_loader import NEF_TIGHT as NEF_TIGHT
    from ida_bytes import doStruct as doStruct
    from ida_bytes import isStkvar as isStkvar
    from ida_kernwin import is_chooser_tform as is_chooser_tform
    from ida_name import demangle_name2 as demangle_name2
    from ida_ida import idainfo as idainfo
    from ida_search import find_void as find_void
    from ida_srarea import del_srarea as del_srarea
    from ida_typeinf import verify_varloc as verify_varloc
    from ida_bytes import isCustFmt as isCustFmt
    from ida_typeinf import PRVLOC_STKOFF as PRVLOC_STKOFF
    from ida_bytes import isOff1 as isOff1
    from ida_ua import get_dtyp_by_size as get_dtyp_by_size
    from ida_bytes import isEnum as isEnum
    from ida_kernwin import PluginForm as PluginForm
    from ida_ida import idainfo as idainfo
    from ida_frame import get_frame_part as get_frame_part
    from ida_netnode import netnode as netnode
    from ida_bytes import byteflag as byteflag
    from ida_nalt import set_switch_info_ex as set_switch_info_ex
    from ida_idp import area_cmt_changed as area_cmt_changed
    from ida_kernwin import askqstr as askqstr
    from ida_enum import CONST_ERROR_VALUE as CONST_ERROR_VALUE
    from ida_bytes import isNum as isNum
    from ida_bytes import chunkstart as chunkstart
    from ida_expr import VarGetSlice as VarGetSlice
    from ida_idp import changed_struc as changed_struc
    from ida_typeinf import optimize_varloc as optimize_varloc
    from ida_bytes import isFltnum as isFltnum
    from ida_srarea import is_segreg_locked as is_segreg_locked
    from ida_bytes import segflag as segflag
    from ida_bytes import numflag as numflag
    from ida_ua import decode_insn as decode_insn
    from ida_typeinf import TERR_TOOLONGNAME as TERR_TOOLONGNAME
    from ida_queue import Q_head as Q_head
    from ida_bytes import f_isQwrd as f_isQwrd
    from ida_ida import ASCF_SERIAL as ASCF_SERIAL
    from ida_bytes import doFloat as doFloat
    from ida_bytes import asciflag as asciflag
    from ida_struct import get_member_tinfo2 as get_member_tinfo2
    from ida_enum import get_const_cmt as get_const_cmt
    from ida_kernwin import HIST_NUM as HIST_NUM
    from ida_typeinf import choose_named_type2 as choose_named_type2
    from ida_bytes import get_zero_areas as get_zero_areas
    from ida_name import extract_name2 as extract_name2
    from ida_bytes import decflag as decflag
    from ida_queue import QueueGetType as QueueGetType
    from ida_bytes import custflag as custflag
    from ida_bytes import hasExtra as hasExtra
    from ida_nalt import RIDX_AUTO_PLUGINS as RIDX_AUTO_PLUGINS
    from ida_name import get_true_name as get_true_name
    from ida_expr import VarGetClassName as VarGetClassName
    from ida_idp import IDP_Hooks as IDP_Hooks
    from ida_enum import CONST_ERROR_NAME as CONST_ERROR_NAME
    from ida_bytes import isStroff1 as isStroff1
    from ida_auto import showAuto as showAuto
    from ida_typeinf import varpart_t as varpart_t
    from ida_bytes import isYwrd as isYwrd
    from ida_bytes import get_next_hidden_area as get_next_hidden_area
    from ida_bytes import isPackReal as isPackReal
    from ida_kernwin import choose2_refresh as choose2_refresh
    from ida_dbg import get_process_info as get_process_info
    from ida_name import is_ident_char as is_ident_char
    from ida_kernwin import _askaddr as _askaddr
    from ida_bytes import enumflag as enumflag
    from ida_bytes import isCustFmt0 as isCustFmt0
    from ida_bytes import isNum1 as isNum1
    from ida_idp import segm_attrs_changed as segm_attrs_changed
    from ida_queue import Q_lines as Q_lines
    from ida_bytes import patch_long as patch_long
    from ida_netnode import netnode as netnode
    from ida_kernwin import chtype_segreg as chtype_segreg
    from ida_netnode import netnode as netnode
    from ida_typeinf import resolve_typedef2 as resolve_typedef2
    from ida_expr import execute as execute
    from ida_idp import removing_func_tail as removing_func_tail
    from ida_bytes import isImmd as isImmd
    from ida_fixup import FIXUP_CREATED as FIXUP_CREATED
    from ida_bytes import get_hidden_area as get_hidden_area
    from ida_ua import op_t as op_t
    from ida_bytes import do_data_ex as do_data_ex
    from ida_bytes import doExtra as doExtra
    from ida_nalt import SWI_BC695_EXTENDED as SWI_BC695_EXTENDED
    from ida_expr import VarCopy as VarCopy
    from ida_typeinf import get_enum_member_expr2 as get_enum_member_expr2
    from ida_bytes import isTail as isTail
    from ida_bytes import isCustom as isCustom
    from ida_segment import segment_t as segment_t
    from ida_ida import idainfo as idainfo
    from ida_bytes import f_isCode as f_isCode
    from ida_ida import AF2_TRFUNC as AF2_TRFUNC
    from ida_kernwin import PluginForm as PluginForm
    from ida_bytes import freechunk as freechunk
    from ida_bytes import add_long as add_long
    from ida_ua import tbo_312 as tbo_312
    from ida_bytes import isFlow as isFlow
    from ida_enum import add_const as add_const
    from ida_ida import scr2idb as scr2idb
    from ida_enum import CONST_ERROR_MASK as CONST_ERROR_MASK
    from ida_kernwin import askfile2_c as askfile2_c
    from ida_bytes import isFop as isFop
    from ida_idd import PROCESS_NO_THREAD as PROCESS_NO_THREAD
    from ida_bytes import noExtra as noExtra
    from ida_typeinf import load_til2 as load_til2
    from ida_bytes import isUnknown as isUnknown
    from ida_expr import VarRef as VarRef
    from ida_enum import get_next_serial_enum_member as get_next_serial_enum_member
    from ida_strlist import refresh_strlist as refresh_strlist
    from ida_bytes import isStroff0 as isStroff0
    from ida_bytes import is3byte as is3byte
    from ida_range import range_t as range_t
    from ida_idp import changed_stkpnts as changed_stkpnts
    from ida_bytes import owrdflag as owrdflag
    from ida_kernwin import choose2_activate as choose2_activate
    from ida_queue import Q_decimp as Q_decimp
    from ida_enum import get_next_serial_const as get_next_serial_const
    from ida_name import get_debug_name2 as get_debug_name2
    from ida_bytes import isSeg1 as isSeg1
    from ida_bytes import prevthat as prevthat
    from ida_bytes import doCustomData as doCustomData
    from ida_typeinf import NTF_NOIDB as NTF_NOIDB
    from ida_ua import get_dtyp_flag as get_dtyp_flag
    from ida_kernwin import askident as askident
    from ida_funcs import del_func_cmt as del_func_cmt
    from ida_idp import SETPROC_FATAL as SETPROC_FATAL
    from ida_bytes import hasValue as hasValue
    from ida_queue import Q_noName as Q_noName
    from ida_enum import get_prev_const as get_prev_const
    from ida_ida import AF2_FTAIL as AF2_FTAIL
    from ida_bytes import chunksize as chunksize
    from ida_bytes import isByte as isByte
    from ida_bytes import tbytflag as tbytflag
    from ida_bytes import FF_VAR as FF_VAR
    from ida_funcs import FUNC_STATIC as FUNC_STATIC
    from ida_ida import ASCF_UNICODE as ASCF_UNICODE
    from ida_funcs import func_setstart as func_setstart
    from ida_nalt import ASCSTR_LEN4 as ASCSTR_LEN4
    from ida_ida import showRepeatables as showRepeatables
    from ida_kernwin import py_get_OpenForm as py_get_OpenForm
    from ida_idaapi import pycim_get_tcustom_control as pycim_get_tcustom_control
    from ida_nalt import ASCSTR_ULEN4 as ASCSTR_ULEN4
    from ida_expr import VarSetSlice as VarSetSlice
    from ida_bytes import prevchunk as prevchunk
    from ida_segment import SEGDEL_KEEP as SEGDEL_KEEP
    from ida_kernwin import PluginForm as PluginForm
    from ida_bytes import nextchunk as nextchunk
    from ida_bytes import isNotTail as isNotTail
    from ida_bytes import doASCI as doASCI
    from ida_expr import py_set_idc_func_ex as py_set_idc_func_ex
    from ida_funcs import clear_func_struct as clear_func_struct
    from ida_bytes import FF_STRU as FF_STRU
    from ida_bytes import FF_TBYT as FF_TBYT
    from ida_bytes import ACFOPT_CONVMASK as ACFOPT_CONVMASK
    from ida_nalt import SWI2_SUBTRACT as SWI2_SUBTRACT
    from ida_ua import cmd as cmd
    from ida_kernwin import askseg as askseg
    from ida_typeinf import const_vloc_visitor_t as const_vloc_visitor_t
    from ida_bytes import nextaddr as nextaddr
    from ida_bytes import dwrdflag as dwrdflag
    from ida_ida import AF_ASCII as AF_ASCII
    from ida_ua import get_operand_immvals as get_operand_immvals
    from ida_bytes import isFloat as isFloat
    from ida_fixup import FIXUP_EXTDEF as FIXUP_EXTDEF
    from ida_bytes import f_isTbyt as f_isTbyt
    from ida_segment import get_true_segm_name as get_true_segm_name
    from ida_queue import Q_collsn as Q_collsn
    from ida_bytes import ACFOPT_ASCII as ACFOPT_ASCII
    from ida_ida import ASCF_COMMENT as ASCF_COMMENT
    from ida_ida import AF2_DATOFF as AF2_DATOFF
    from ida_kernwin import chtype_generic2 as chtype_generic2
    from ida_ida import INFFL_LZERO as INFFL_LZERO
    from ida_expr import VarSwap as VarSwap
    from ida_nalt import get_switch_info_ex as get_switch_info_ex
    from ida_ida import idainfo as idainfo
    from ida_bytes import f_isNotTail as f_isNotTail
    from ida_funcs import func_setend as func_setend
    from ida_idp import NEXTEAS_ANSWER_SIZE as NEXTEAS_ANSWER_SIZE
    from ida_typeinf import find_tinfo_udt_member as find_tinfo_udt_member
    from ida_frame import add_auto_stkpnt2 as add_auto_stkpnt2
    from ida_ua import codeSeg as codeSeg
    from ida_bytes import isFloat1 as isFloat1
    from ida_ua import tbo_321 as tbo_321
    from ida_ida import ASCF_GEN as ASCF_GEN
    from ida_bytes import f_hasRef as f_hasRef
    from ida_bytes import get_original_long as get_original_long
    from ida_queue import Q_Qnum as Q_Qnum
    from ida_queue import QueueDel as QueueDel
    from ida_kernwin import PluginForm as PluginForm
    from ida_ida import AF2_DODATA as AF2_DODATA
    from ida_bytes import f_isOwrd as f_isOwrd
    from ida_idp import parse_reg_name as parse_reg_name
    from ida_nalt import ASCSTR_PASCAL as ASCSTR_PASCAL
    from ida_lines import describe as describe
    from ida_ua import UA_MAXOP as UA_MAXOP
    from ida_kernwin import choose2_close as choose2_close
    from ida_bytes import get_many_bytes_ex as get_many_bytes_ex
    from ida_kernwin import clearBreak as clearBreak
    from ida_bytes import DOUNK_NOTRUNC as DOUNK_NOTRUNC
    from ida_typeinf import varloc_t as varloc_t
    from ida_funcs import func_parent_iterator_set2 as func_parent_iterator_set2
    from ida_graph import del_node_info2 as del_node_info2
    from ida_bytes import put_long as put_long
    from ida_bytes import do32bit as do32bit
    from ida_hexrays import get_tform_vdui as get_tform_vdui
    from ida_srarea import get_srareas_qty2 as get_srareas_qty2
    from ida_bytes import isDefArg1 as isDefArg1
    from ida_enum import get_first_serial_const as get_first_serial_const
    from ida_kernwin import _asklong as _asklong
    from ida_bytes import isSeg0 as isSeg0
    from ida_bytes import ywrdflag as ywrdflag
    from ida_bytes import fltflag as fltflag
    from ida_nalt import switch_info_t as switch_info_t
    from ida_typeinf import save_tinfo as save_tinfo
    from ida_ida import idainfo as idainfo
    from ida_kernwin import PluginForm as PluginForm
    from ida_bytes import octflag as octflag
    from ida_bytes import patch_many_bytes as patch_many_bytes
    from ida_typeinf import apply_cdecl2 as apply_cdecl2
    from ida_expr import Compile as Compile
    from ida_typeinf import BFI_NOCONST as BFI_NOCONST
    from ida_bytes import isZwrd as isZwrd
    from ida_bytes import doQwrd as doQwrd
    from ida_kernwin import Choose2 as Choose2
    from ida_bytes import tribyteflag as tribyteflag
    from ida_nalt import ASCSTR_LEN2 as ASCSTR_LEN2
    from ida_ua import decode_prev_insn as decode_prev_insn
    from ida_nalt import ASCSTR_LAST as ASCSTR_LAST
    from ida_typeinf import extract_varloc as extract_varloc
    from ida_funcs import func_t as func_t
    from ida_bytes import getn_hidden_area as getn_hidden_area
    from ida_ida import showComments as showComments
    from ida_ida import idainfo as idainfo
    from ida_bytes import doWord as doWord
    from ida_expr import VarPrint as VarPrint
    from ida_bytes import FF_OWRD as FF_OWRD
    from ida_srarea import get_prev_srarea as get_prev_srarea
    from ida_offset import calc_reference_basevalue as calc_reference_basevalue
    from ida_kernwin import askaddr as askaddr
    from ida_bytes import packrealflag as packrealflag
    from ida_typeinf import guess_tinfo as guess_tinfo
    from ida_kernwin import KERNEL_VERSION_MAGIC2 as KERNEL_VERSION_MAGIC2
    from ida_nalt import get_encodings_count as get_encodings_count
    from ida_struct import get_member_name2 as get_member_name2
    from ida_kernwin import get_tform_title as get_tform_title
    from ida_name import demangle_name as demangle_name
    from ida_kernwin import CB_CLOSE_IDB as CB_CLOSE_IDB
    from ida_bytes import get_full_word as get_full_word
    from ida_bytes import FF_DWRD as FF_DWRD
    from ida_name import is_visible_char as is_visible_char
    from ida_idp import SETPROC_ALL as SETPROC_ALL
    from ida_enum import get_next_const as get_next_const
    from ida_expr import VarPrevAttr as VarPrevAttr
    from ida_expr import VarDelAttr as VarDelAttr
    from ida_bytes import get_full_long as get_full_long
    from ida_idp import func_tail_removed as func_tail_removed
    from ida_netnode import netnode as netnode
    from ida_kernwin import UI_Hooks as UI_Hooks
    from ida_bytes import binflag as binflag
    from ida_ida import AF2_SIGMLT as AF2_SIGMLT
    from ida_idaapi import pycim_get_tform as pycim_get_tform
    from ida_enum import CONST_ERROR_ILLV as CONST_ERROR_ILLV
    from ida_bytes import f_isWord as f_isWord
    from ida_enum import get_const_value as get_const_value
    from ida_typeinf import guess_tinfo2 as guess_tinfo2
    from ida_ida import idainfo as idainfo
    from ida_bytes import doImmd as doImmd
    from ida_bytes import get_hidden_area_qty as get_hidden_area_qty
    from ida_ida import idb2scr as idb2scr
    from ida_name import do_name_anyway as do_name_anyway
    from ida_bytes import do_unknown_range as do_unknown_range
    from ida_bytes import doVar as doVar
    from ida_ida import idainfo as idainfo
    from ida_bytes import f_isByte as f_isByte
    from ida_bytes import isFloat0 as isFloat0
    from ida_kernwin import find_tform as find_tform
    from ida_auto import setStat as setStat
    from ida_hexrays import hx_get_tform_vdui as hx_get_tform_vdui
    from ida_fixup import FIXUP_REL as FIXUP_REL
    from ida_ua import create_insn as create_insn
    from ida_enum import get_const_bmask as get_const_bmask
    from ida_bytes import doAlign as doAlign
    from ida_typeinf import vloc_visitor_t as vloc_visitor_t
    from ida_bytes import ACFOPT_UTF16 as ACFOPT_UTF16
    from ida_bytes import doPackReal as doPackReal
    from ida_bytes import isAlign as isAlign
    from ida_queue import Q_rolled as Q_rolled
    from ida_ua import tbo_231 as tbo_231
    from ida_ida import idainfo as idainfo
    from ida_ida import idainfo as idainfo
    from ida_ida import AF2_STKARG as AF2_STKARG
    from ida_kernwin import UI_Hooks as UI_Hooks
    from ida_enum import del_const as del_const
    from ida_ida import idainfo as idainfo
    from ida_ida import idainfo as idainfo
    from ida_bytes import doByte as doByte
    from ida_bytes import isChar0 as isChar0
    from ida_nalt import get_tinfo2 as get_tinfo2
    from ida_ua import ua_add_dref as ua_add_dref
    from ida_name import GN_INSNLOC as GN_INSNLOC
    from ida_bytes import FF_ZWRD as FF_ZWRD
    from ida_bytes import prevaddr as prevaddr
    from ida_srarea import getn_srarea2 as getn_srarea2
    from ida_bytes import get_prev_hidden_area as get_prev_hidden_area
    from ida_kernwin import AST_DISABLE_FOR_FORM as AST_DISABLE_FOR_FORM
    from ida_enum import get_prev_serial_enum_member as get_prev_serial_enum_member
    from ida_ua import dt_3byte as dt_3byte
    from ida_bytes import floatflag as floatflag
    from ida_bytes import doZwrd as doZwrd
    from ida_ua import ua_dodata2 as ua_dodata2
    from ida_bytes import f_is3byte as f_is3byte
    from ida_bytes import get_ascii_contents2 as get_ascii_contents2
    from ida_ida import ansi2idb as ansi2idb
    from ida_typeinf import apply_decl as apply_decl
    from ida_kernwin import switchto_tform as switchto_tform
    from ida_ida import idainfo as idainfo
    from ida_bytes import getRadix as getRadix
    from ida_idp import PR_FULL_HIFXP as PR_FULL_HIFXP
    from ida_idp import get_reg_info2 as get_reg_info2
    from ida_bytes import alignflag as alignflag
    from ida_bytes import DOUNK_DELNAMES as DOUNK_DELNAMES
    from ida_name import validate_name3 as validate_name3
    from ida_bytes import get_full_byte as get_full_byte
    from ida_nalt import set_tinfo2 as set_tinfo2
    from ida_expr import VT_STR2 as VT_STR2
    from ida_nalt import switch_info_t as switch_info_t
    from ida_expr import VarFirstAttr as VarFirstAttr
    from ida_ida import idainfo as idainfo
    from ida_nalt import get_tinfo as get_tinfo
    from ida_idp import ph_get_regLastSreg as ph_get_regLastSreg
    from ida_enum import get_const_enum as get_const_enum
    from ida_enum import get_last_const as get_last_const
    from ida_idp import AS_NOTAB as AS_NOTAB
    from ida_funcs import func_t as func_t
    from ida_nalt import del_switch_info_ex as del_switch_info_ex
    from ida_srarea import SetDefaultRegisterValue as SetDefaultRegisterValue
    from ida_ida import AF2_DOCODE as AF2_DOCODE
    from ida_typeinf import lower_type2 as lower_type2
    from ida_segment import del_segment_cmt as del_segment_cmt
    from ida_ua import get_dtyp_size as get_dtyp_size
    from ida_funcs import add_regarg2 as add_regarg2
    from ida_ua import ua_stkvar2 as ua_stkvar2
    from ida_bytes import isFunc as isFunc
    from ida_bytes import f_isHead as f_isHead
    from ida_typeinf import BFI_NOLOCS as BFI_NOLOCS
    from ida_offset import calc_reference_target as calc_reference_target
    from ida_srarea import copy_srareas as copy_srareas
    from ida_ida import AF2_CHKUNI as AF2_CHKUNI
    from ida_struct import get_member_tinfo as get_member_tinfo
    from ida_bytes import f_isStruct as f_isStruct
    from ida_typeinf import find_udt_member as find_udt_member
    from ida_kernwin import setBreak as setBreak
    from ida_bytes import struflag as struflag
    from ida_bytes import noType as noType
    from ida_auto import analyze_area as analyze_area
    from ida_auto import showAddr as showAddr
    from ida_kernwin import KERNEL_VERSION_MAGIC1 as KERNEL_VERSION_MAGIC1
    from ida_kernwin import PluginForm as PluginForm
    from ida_queue import Q_noRef as Q_noRef
    from ida_bytes import zwrdflag as zwrdflag
    from ida_bytes import isDefArg as isDefArg
    from ida_srarea import getSR as getSR
    from ida_kernwin import UI_Hooks as UI_Hooks
    from ida_idp import changing_struc as changing_struc
    from ida_bytes import isStkvar0 as isStkvar0
    from ida_netnode import netnode as netnode
    from ida_kernwin import UI_Hooks as UI_Hooks
    from ida_bytes import f_isCustom as f_isCustom
    from ida_queue import Q_noValid as Q_noValid
    from ida_bytes import isOff0 as isOff0
    from ida_queue import Q_noBase as Q_noBase
    from ida_bytes import isQwrd as isQwrd
    from ida_queue import Q_disasm as Q_disasm
    from ida_bytes import isOff as isOff
    from ida_graph import clr_node_info2 as clr_node_info2
    from ida_bytes import delValue as delValue
    from ida_kernwin import PluginForm as PluginForm
    from ida_ida import idainfo as idainfo
    from ida_kernwin import UI_Hooks as UI_Hooks
    from ida_ida import AF2_PURDAT as AF2_PURDAT
    from ida_queue import Q_noComm as Q_noComm
    from ida_bytes import isSeg as isSeg
    from ida_name import make_visible_name as make_visible_name
    from ida_auto import autoCancel as autoCancel
    from ida_bytes import f_isPackReal as f_isPackReal
    from ida_typeinf import calc_c_cpp_name4 as calc_c_cpp_name4
    from ida_frame import get_stkvar as get_stkvar
    from ida_netnode import netnode as netnode
    from ida_bytes import isDwrd as isDwrd
    from ida_netnode import netnode as netnode
    from ida_struct import get_or_guess_member_tinfo2 as get_or_guess_member_tinfo2
    from ida_segment import ask_selected as ask_selected
    from ida_ida import idainfo as idainfo
    from ida_netnode import netnode as netnode
    from ida_expr import VarObject as VarObject
    from ida_typeinf import choose_local_type as choose_local_type
    from ida_bytes import ACFOPT_ESCAPE as ACFOPT_ESCAPE
